apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repository
  namespace: argo
data:
  default: |
    s3:
      bucket: weather-forecast-ai-prod-ml-data
      endpoint: s3.amazonaws.com
      region: ap-northeast-1
      useSDKCreds: true
      keyFormat: "logs/argo-workflows/{{workflow.name}}/{{pod.name}}"
