apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-lbc
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: "2.x.x"
    helm:
      parameters:
        - name: clusterName
          value: REPLACE_WITH_CLUSTER_NAME
        - name: vpcId
          value: REPLACE_WITH_VPC_ID
        - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: REPLACE_WITH_LBC_IRSA_ARN
        - name: serviceAccount.create
          value: "true"
        - name: serviceAccount.name
          value: aws-load-balancer-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
