apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: public.ecr.aws/karpenter
    chart: karpenter
    targetRevision: "1.6.6"
    helm:
      valuesObject:
        settings:
          clusterName: REPLACE_WITH_CLUSTER_NAME
          interruptionQueue: REPLACE_WITH_CLUSTER_NAME-karpenter
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: REPLACE_WITH_KARPENTER_ROLE_ARN
        replicas: 1
        controller:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
