apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: weather-forecast-ai-prod-ml-data
      endpoint: s3.amazonaws.com
      region: ap-northeast-1
      useSDKCreds: true
      keyFormat: "logs/argo-workflows/{{workflow.name}}/{{pod.name}}"
