apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mlflow
resources:
  - ../../../base/mlflow
patches:
  - patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: mlflow
        annotations:
          eks.amazonaws.com/role-arn: REPLACE_WITH_MLFLOW_IRSA_ARN
    target:
      kind: ServiceAccount
      name: mlflow
images:
  - name: REPLACE_WITH_ECR_MLFLOW_URL
    newName: REPLACE_WITH_ECR_MLFLOW_URL
    newTag: latest
